### ISSUE TITLE
Filenames with spaces causing problems

### ISSUE THREAD

**Issue by wyvern1969** [ManiaControl/ManiaControl#233] opened 2020-02-23 11:40 UTC
Hello,
I installed the latest version of Maniacontrol.
The button "Directory Browser, "Check MX for updates", "Maps name" and "Author"do not work.
I don't understand why.
Sorry for my English
Thank you for your help.
Wyvern

**Comment by kremsy** [comment] 2020-02-23 12:10
Thanks for your report!

Are there any errors in the logfile?

**Comment by wyvern1969** [comment] 2020-02-23 15:17
This is the log after test with a different buttons.

[23-Feb-2020 15:12:22 UTC] Starting ManiaControl...
[23-Feb-2020 15:12:22 UTC] Checking for minimum required PHP-Version 5.4 ... 5.6.40 OK!
[23-Feb-2020 15:12:22 UTC] Checking for installed MySQLi ... FOUND!
[23-Feb-2020 15:12:22 UTC] Checking for installed cURL ... FOUND!
[23-Feb-2020 15:12:22 UTC] Checking for installed PHP ZIP ... FOUND!
[23-Feb-2020 15:12:22 UTC] Checking for installed Zlib ... FOUND!
[23-Feb-2020 15:12:22 UTC] Checking for installed mbstring ... FOUND!
[23-Feb-2020 15:12:22 UTC] Loading ManiaControl v0.231 ...
[23-Feb-2020 15:12:23 UTC] Starting ManiaControl v0.231!
[23-Feb-2020 15:12:23 UTC] Connecting to Server at 127.0.0.1:5070...
[23-Feb-2020 15:12:23 UTC] Server Connection successfully established!
[23-Feb-2020 15:12:23 UTC] [INFO] Script Callbacks successfully enabled!
[23-Feb-2020 15:12:23 UTC] [INFO] Server Options successfully loaded!
[23-Feb-2020 15:12:23 UTC] Put Race Ranking Widget to custom position
[23-Feb-2020 15:12:23 UTC] Hide Spec Icon
[23-Feb-2020 15:12:23 UTC] [INFO] Try to connect on Dedimania
[23-Feb-2020 15:12:23 UTC] Checking Plugins for newer Versions...
[23-Feb-2020 15:12:23 UTC] Loading completed!
[23-Feb-2020 15:12:23 UTC] Link: maniaplanet://#join=wyvern1969@TMStadium@nadeo
[23-Feb-2020 15:12:25 UTC] Can load LRCPLive plugin
[23-Feb-2020 15:12:25 UTC] Can load LRCPLive Dedimania plugin
[23-Feb-2020 15:12:25 UTC] [INFO] Dedimania connection successfully established.
[23-Feb-2020 15:12:25 UTC] Plugins Update Check completed: All Plugins are up-to-date!
[23-Feb-2020 15:12:25 UTC] Successfully authenticated on Mania-Exchange Karma
[23-Feb-2020 15:12:25 UTC] [INFO] MX-Karma Votes successfully fetched!
[23-Feb-2020 15:15:10 UTC] [INFO] Player joined: wivern / "ŊΩŊ" ฝŷѷӗřŋ Nation: Belgium IP: 80.201.117.163:2350
[23-Feb-2020 15:15:10 UTC] [INFO] Try to fetch Dedimania Records
[23-Feb-2020 15:15:10 UTC] [INFO] Dedimania Player added wivern
[23-Feb-2020 15:15:10 UTC] [INFO] 5 Dedimania Records Fetched succesfully!
[23-Feb-2020 15:15:10 UTC] [INFO] MX-Karma Votes successfully fetched!
[23-Feb-2020 15:15:30 UTC] [PHP WARNING]: DOMElement::setAttribute(): string is not in UTF-8
File&Line: C:\Program Files (x86)\Serveur Maniaplanet Steph\ManiaControl-0.301\libs\FML\Controls\Label.php: 634
Trace: 
#0: DOMElement->setAttribute(string(text), string(your dirt TM².Map.Gbx)) in File libs\FML\Controls\Label.php on Line 634
#1: FML\Controls\Label->render(object(DOMDocument)) in File libs\FML\Controls\Frame.php on Line 153
#2: FML\Controls\Frame->render(object(DOMDocument)) in File libs\FML\Controls\Frame.php on Line 153
#3: FML\Controls\Frame->render(object(DOMDocument)) in File libs\FML\Controls\Frame.php on Line 153
#4: FML\Controls\Frame->render(object(DOMDocument)) in File libs\FML\ManiaLink.php on Line 559
#5: FML\ManiaLink->render() in File libs\FML\ManiaLink.php on Line 600
#6: FML\ManiaLink->__toString() in File core\Manialinks\ManialinkManager.php on Line 246
#7: ManiaControl\Manialinks\ManialinkManager->sendManialink(object(FML\ManiaLink), object(ManiaControl\Players\Player)) in File core\Manialinks\ManialinkManager.php on Line 219
#8: ManiaControl\Manialinks\ManialinkManager->displayWidget(object(FML\ManiaLink), object(ManiaControl\Players\Player), string(MapsDirBrowser.Widget)) in File core\Maps\DirectoryBrowser.php on Line 234
#9: ManiaControl\Maps\DirectoryBrowser->showManiaLink(object(ManiaControl\Players\Player)) in File core\Maps\DirectoryBrowser.php on Line 86
#10: ManiaControl\Maps\DirectoryBrowser->handleActionShow(array(string(ManiaPlanet.PlayerManialinkPageAnswer), array(integer(180), string(wivern), string(MapsDirBrowser.Show), array(array(string(SearchString), string(), )))...), ...)
#11: call_user_func(array(object(ManiaControl\Maps\DirectoryBrowser), string(handleActionShow)), array(string(ManiaPlanet.PlayerManialinkPageAnswer), array(integer(180), string(wivern), string(MapsDirBrowser.Show), array(array(string(SearchString), string(), )))...), ...) in File core\Manialinks\ManialinkManager.php on Line 195
#12: ManiaControl\Manialinks\ManialinkManager->handleManialinkPageAnswer(array(string(ManiaPlanet.PlayerManialinkPageAnswer), array(integer(180), string(wivern), string(MapsDirBrowser.Show), array(array(string(SearchString), string(), )))...)...)
#13: call_user_func_array(array(object(ManiaControl\Manialinks\ManialinkManager), string(handleManialinkPageAnswer)), array(array(string(ManiaPlanet.PlayerManialinkPageAnswer), array(integer(180), string(wivern), string(MapsDirBrowser.Show), array(array(string(SearchString), string(), )))...)...)...) in File core\Callbacks\Listening.php on Line 68
#14: ManiaControl\Callbacks\Listening->triggerCallbackWithParams(array(array(string(ManiaPlanet.PlayerManialinkPageAnswer), array(integer(180), string(wivern), string(MapsDirBrowser.Show), array(array(string(SearchString), string(), )))...)...)...) in File core\Callbacks\CallbackManager.php on Line 325
...
[23-Feb-2020 15:15:30 UTC] PHP Warning:  DOMElement::setAttribute(): string is not in UTF-8 in C:\Program Files (x86)\Serveur Maniaplanet Steph\ManiaControl-0.301\libs\FML\Controls\Label.php on line 634
[23-Feb-2020 15:15:30 UTC] [PHP WARNING]: DOMElement::setAttribute(): string is not in UTF-8
File&Line: C:\Program Files (x86)\Serveur Maniaplanet Steph\ManiaControl-0.301\libs\FML\Controls\Label.php: 652
Trace: 
#0: DOMElement->setAttribute(string(action), string(MapsDirBrowser.InspectFile.your dirt TM²..)) in File libs\FML\Controls\Label.php on Line 652
#1: FML\Controls\Label->render(object(DOMDocument)) in File libs\FML\Controls\Frame.php on Line 153
#2: FML\Controls\Frame->render(object(DOMDocument)) in File libs\FML\Controls\Frame.php on Line 153
#3: FML\Controls\Frame->render(object(DOMDocument)) in File libs\FML\Controls\Frame.php on Line 153
#4: FML\Controls\Frame->render(object(DOMDocument)) in File libs\FML\ManiaLink.php on Line 559
#5: FML\ManiaLink->render() in File libs\FML\ManiaLink.php on Line 600
#6: FML\ManiaLink->__toString() in File core\Manialinks\ManialinkManager.php on Line 246
#7: ManiaControl\Manialinks\ManialinkManager->sendManialink(object(FML\ManiaLink), object(ManiaControl\Players\Player)) in File core\Manialinks\ManialinkManager.php on Line 219
#8: ManiaControl\Manialinks\ManialinkManager->displayWidget(object(FML\ManiaLink), object(ManiaControl\Players\Player), string(MapsDirBrowser.Widget)) in File core\Maps\DirectoryBrowser.php on Line 234
#9: ManiaControl\Maps\DirectoryBrowser->showManiaLink(object(ManiaControl\Players\Player)) in File core\Maps\DirectoryBrowser.php on Line 86
#10: ManiaControl\Maps\DirectoryBrowser->handleActionShow(array(string(ManiaPlanet.PlayerManialinkPageAnswer), array(integer(180), string(wivern), string(MapsDirBrowser.Show), array(array(string(SearchString), string(), )))...), ...)
#11: call_user_func(array(object(ManiaControl\Maps\DirectoryBrowser), string(handleActionShow)), array(string(ManiaPlanet.PlayerManialinkPageAnswer), array(integer(180), string(wivern), string(MapsDirBrowser.Show), array(array(string(SearchString), string(), )))...), ...) in File core\Manialinks\ManialinkManager.php on Line 195
#12: ManiaControl\Manialinks\ManialinkManager->handleManialinkPageAnswer(array(string(ManiaPlanet.PlayerManialinkPageAnswer), array(integer(180), string(wivern), string(MapsDirBrowser.Show), array(array(string(SearchString), string(), )))...)...)
#13: call_user_func_array(array(object(ManiaControl\Manialinks\ManialinkManager), string(handleManialinkPageAnswer)), array(array(string(ManiaPlanet.PlayerManialinkPageAnswer), array(integer(180), string(wivern), string(MapsDirBrowser.Show), array(array(string(SearchString), string(), )))...)...)...) in File core\Callbacks\Listening.php on Line 68
#14: ManiaControl\Callbacks\Listening->triggerCallbackWithParams(array(array(string(ManiaPlanet.PlayerManialinkPageAnswer), array(integer(180), string(wivern), string(MapsDirBrowser.Show), array(array(string(SearchString), string(), )))...)...)...) in File core\Callbacks\CallbackManager.php on Line 325
...
[23-Feb-2020 15:15:30 UTC] PHP Warning:  DOMElement::setAttribute(): string is not in UTF-8 in C:\Program Files (x86)\Serveur Maniaplanet Steph\ManiaControl-0.301\libs\FML\Controls\Label.php on line 652
[23-Feb-2020 15:15:30 UTC] [PHP WARNING]: DOMElement::setAttribute(): string is not in UTF-8
File&Line: C:\Program Files (x86)\Serveur Maniaplanet Steph\ManiaControl-0.301\libs\FML\Controls\Quad.php: 747
Trace: 
#0: DOMElement->setAttribute(string(action), string(MapsDirBrowser.AddFile.your dirt TM².Map..)) in File libs\FML\Controls\Quad.php on Line 747
#1: FML\Controls\Quad->render(object(DOMDocument)) in File libs\FML\Controls\Frame.php on Line 153
#2: FML\Controls\Frame->render(object(DOMDocument)) in File libs\FML\Controls\Frame.php on Line 153
#3: FML\Controls\Frame->render(object(DOMDocument)) in File libs\FML\Controls\Frame.php on Line 153
#4: FML\Controls\Frame->render(object(DOMDocument)) in File libs\FML\ManiaLink.php on Line 559
#5: FML\ManiaLink->render() in File libs\FML\ManiaLink.php on Line 600
#6: FML\ManiaLink->__toString() in File core\Manialinks\ManialinkManager.php on Line 246
#7: ManiaControl\Manialinks\ManialinkManager->sendManialink(object(FML\ManiaLink), object(ManiaControl\Players\Player)) in File core\Manialinks\ManialinkManager.php on Line 219
#8: ManiaControl\Manialinks\ManialinkManager->displayWidget(object(FML\ManiaLink), object(ManiaControl\Players\Player), string(MapsDirBrowser.Widget)) in File core\Maps\DirectoryBrowser.php on Line 234
#9: ManiaControl\Maps\DirectoryBrowser->showManiaLink(object(ManiaControl\Players\Player)) in File core\Maps\DirectoryBrowser.php on Line 86
#10: ManiaControl\Maps\DirectoryBrowser->handleActionShow(array(string(ManiaPlanet.PlayerManialinkPageAnswer), array(integer(180), string(wivern), string(MapsDirBrowser.Show), array(array(string(SearchString), string(), )))...), ...)
#11: call_user_func(array(object(ManiaControl\Maps\DirectoryBrowser), string(handleActionShow)), array(string(ManiaPlanet.PlayerManialinkPageAnswer), array(integer(180), string(wivern), string(MapsDirBrowser.Show), array(array(string(SearchString), string(), )))...), ...) in File core\Manialinks\ManialinkManager.php on Line 195
#12: ManiaControl\Manialinks\ManialinkManager->handleManialinkPageAnswer(array(string(ManiaPlanet.PlayerManialinkPageAnswer), array(integer(180), string(wivern), string(MapsDirBrowser.Show), array(array(string(SearchString), string(), )))...)...)
#13: call_user_func_array(array(object(ManiaControl\Manialinks\ManialinkManager), string(handleManialinkPageAnswer)), array(array(string(ManiaPlanet.PlayerManialinkPageAnswer), array(integer(180), string(wivern), string(MapsDirBrowser.Show), array(array(string(SearchString), string(), )))...)...)...) in File core\Callbacks\Listening.php on Line 68
#14: ManiaControl\Callbacks\Listening->triggerCallbackWithParams(array(array(string(ManiaPlanet.PlayerManialinkPageAnswer), array(integer(180), string(wivern), string(MapsDirBrowser.Show), array(array(string(SearchString), string(), )))...)...)...) in File core\Callbacks\CallbackManager.php on Line 325
...
[23-Feb-2020 15:15:30 UTC] PHP Warning:  DOMElement::setAttribute(): string is not in UTF-8 in C:\Program Files (x86)\Serveur Maniaplanet Steph\ManiaControl-0.301\libs\FML\Controls\Quad.php on line 747
[23-Feb-2020 15:15:30 UTC] [PHP WARNING]: DOMElement::setAttribute(): string is not in UTF-8
File&Line: C:\Program Files (x86)\Serveur Maniaplanet Steph\ManiaControl-0.301\libs\FML\Controls\Quad.php: 747
Trace: 
#0: DOMElement->setAttribute(string(action), string(MapsDirBrowser.EraseFile.your dirt TM².M..)) in File libs\FML\Controls\Quad.php on Line 747
#1: FML\Controls\Quad->render(object(DOMDocument)) in File libs\FML\Controls\Frame.php on Line 153
#2: FML\Controls\Frame->render(object(DOMDocument)) in File libs\FML\Controls\Frame.php on Line 153
#3: FML\Controls\Frame->render(object(DOMDocument)) in File libs\FML\Controls\Frame.php on Line 153
#4: FML\Controls\Frame->render(object(DOMDocument)) in File libs\FML\ManiaLink.php on Line 559
#5: FML\ManiaLink->render() in File libs\FML\ManiaLink.php on Line 600
#6: FML\ManiaLink->__toString() in File core\Manialinks\ManialinkManager.php on Line 246
#7: ManiaControl\Manialinks\ManialinkManager->sendManialink(object(FML\ManiaLink), object(ManiaControl\Players\Player)) in File core\Manialinks\ManialinkManager.php on Line 219
#8: ManiaControl\Manialinks\ManialinkManager->displayWidget(object(FML\ManiaLink), object(ManiaControl\Players\Player), string(MapsDirBrowser.Widget)) in File core\Maps\DirectoryBrowser.php on Line 234
#9: ManiaControl\Maps\DirectoryBrowser->showManiaLink(object(ManiaControl\Players\Player)) in File core\Maps\DirectoryBrowser.php on Line 86
#10: ManiaControl\Maps\DirectoryBrowser->handleActionShow(array(string(ManiaPlanet.PlayerManialinkPageAnswer), array(integer(180), string(wivern), string(MapsDirBrowser.Show), array(array(string(SearchString), string(), )))...), ...)
#11: call_user_func(array(object(ManiaControl\Maps\DirectoryBrowser), string(handleActionShow)), array(string(ManiaPlanet.PlayerManialinkPageAnswer), array(integer(180), string(wivern), string(MapsDirBrowser.Show), array(array(string(SearchString), string(), )))...), ...) in File core\Manialinks\ManialinkManager.php on Line 195
#12: ManiaControl\Manialinks\ManialinkManager->handleManialinkPageAnswer(array(string(ManiaPlanet.PlayerManialinkPageAnswer), array(integer(180), string(wivern), string(MapsDirBrowser.Show), array(array(string(SearchString), string(), )))...)...)
#13: call_user_func_array(array(object(ManiaControl\Manialinks\ManialinkManager), string(handleManialinkPageAnswer)), array(array(string(ManiaPlanet.PlayerManialinkPageAnswer), array(integer(180), string(wivern), string(MapsDirBrowser.Show), array(array(string(SearchString), string(), )))...)...)...) in File core\Callbacks\Listening.php on Line 68
#14: ManiaControl\Callbacks\Listening->triggerCallbackWithParams(array(array(string(ManiaPlanet.PlayerManialinkPageAnswer), array(integer(180), string(wivern), string(MapsDirBrowser.Show), array(array(string(SearchString), string(), )))...)...)...) in File core\Callbacks\CallbackManager.php on Line 325
...
[23-Feb-2020 15:15:30 UTC] PHP Warning:  DOMElement::setAttribute(): string is not in UTF-8 in C:\Program Files (x86)\Serveur Maniaplanet Steph\ManiaControl-0.301\libs\FML\Controls\Quad.php on line 747
[23-Feb-2020 15:15:30 UTC] [PHP WARNING]: DOMDocument::saveXML(): output conversion failed due to conv error, bytes 0xB2 0x2E 0x4D 0x61
File&Line: C:\Program Files (x86)\Serveur Maniaplanet Steph\ManiaControl-0.301\libs\FML\ManiaLink.php: 601
Trace: 
#0: DOMDocument->saveXML() in File libs\FML\ManiaLink.php on Line 601
#1: FML\ManiaLink->__toString() in File core\Manialinks\ManialinkManager.php on Line 246
#2: ManiaControl\Manialinks\ManialinkManager->sendManialink(object(FML\ManiaLink), object(ManiaControl\Players\Player)) in File core\Manialinks\ManialinkManager.php on Line 219
#3: ManiaControl\Manialinks\ManialinkManager->displayWidget(object(FML\ManiaLink), object(ManiaControl\Players\Player), string(MapsDirBrowser.Widget)) in File core\Maps\DirectoryBrowser.php on Line 234
#4: ManiaControl\Maps\DirectoryBrowser->showManiaLink(object(ManiaControl\Players\Player)) in File core\Maps\DirectoryBrowser.php on Line 86
#5: ManiaControl\Maps\DirectoryBrowser->handleActionShow(array(string(ManiaPlanet.PlayerManialinkPageAnswer), array(integer(180), string(wivern), string(MapsDirBrowser.Show), array(array(string(SearchString), string(), )))...), ...)
#6: call_user_func(array(object(ManiaControl\Maps\DirectoryBrowser), string(handleActionShow)), array(string(ManiaPlanet.PlayerManialinkPageAnswer), array(integer(180), string(wivern), string(MapsDirBrowser.Show), array(array(string(SearchString), string(), )))...), ...) in File core\Manialinks\ManialinkManager.php on Line 195
#7: ManiaControl\Manialinks\ManialinkManager->handleManialinkPageAnswer(array(string(ManiaPlanet.PlayerManialinkPageAnswer), array(integer(180), string(wivern), string(MapsDirBrowser.Show), array(array(string(SearchString), string(), )))...)...)
#8: call_user_func_array(array(object(ManiaControl\Manialinks\ManialinkManager), string(handleManialinkPageAnswer)), array(array(string(ManiaPlanet.PlayerManialinkPageAnswer), array(integer(180), string(wivern), string(MapsDirBrowser.Show), array(array(string(SearchString), string(), )))...)...)...) in File core\Callbacks\Listening.php on Line 68
#9: ManiaControl\Callbacks\Listening->triggerCallbackWithParams(array(array(string(ManiaPlanet.PlayerManialinkPageAnswer), array(integer(180), string(wivern), string(MapsDirBrowser.Show), array(array(string(SearchString), string(), )))...)...)...) in File core\Callbacks\CallbackManager.php on Line 325
#10: ManiaControl\Callbacks\CallbackManager->triggerCallback(string(ManiaPlanet.PlayerManialinkPageAnswer), array(string(ManiaPlanet.PlayerManialinkPageAnswer), array(integer(180), string(wivern), string(MapsDirBrowser.Show), array(array(string(SearchString), string(), )))...)...) in File core\Callbacks\CallbackManager.php on Line 304
#11: ManiaControl\Callbacks\CallbackManager->handleCallback(array(string(ManiaPlanet.PlayerManialinkPageAnswer), array(integer(180), string(wivern), string(MapsDirBrowser.Show), array(array(string(SearchString), string(), )))...)...) in File core\Callbacks\CallbackManager.php on Line 253
...
[23-Feb-2020 15:15:30 UTC] PHP Warning:  DOMDocument::saveXML(): output conversion failed due to conv error, bytes 0xB2 0x2E 0x4D 0x61 in C:\Program Files (x86)\Serveur Maniaplanet Steph\ManiaControl-0.301\libs\FML\ManiaLink.php on line 601
[23-Feb-2020 15:15:30 UTC] Error-Report successful!
[23-Feb-2020 15:15:30 UTC] Error-Report successful!
[23-Feb-2020 15:15:30 UTC] Error-Report successful!
[23-Feb-2020 15:15:30 UTC] Error-Report successful!
[23-Feb-2020 15:15:30 UTC] Error-Report successful!

**Comment by kremsy** [comment] 2020-02-23 19:00
Is the issue solved or why did you close it?

**Comment by wyvern1969** [comment] 2020-02-24 08:55
Hello,
Sorry, it is not close.
Wyvern

**Comment by kremsy** [comment] 2020-02-24 19:54
Looks like there is a map name without Beeing a utf8 name.

**Comment by wyvern1969** [comment] 2020-02-25 15:33
Hello,
I check each name maps and i modify 2 maps.
It doesn't work.
I think, the name map is not a problem.
Refards

**Comment by kremsy** [comment] 2020-02-25 15:36
2 possible problems:

your dirt TM².Map.Gbx

1) Spaces in the mapname
2) the ²

Seems multipe maps have these in the filename.

**Comment by wyvern1969** [comment] 2020-02-26 06:56
Hi,
I test this morning just with 1 map in my matchsetting.
The name map is "Grece.Map.Gbx"
I have again a same problem ....
Regards

**Comment by wyvern1969** [comment] 2020-02-26 10:36
After somes tests, now it's OK.
But, i don't understand why the space in the name map it's problem.
Wyvern

**Comment by kremsy** [comment] 2020-02-26 12:00
Filenames should never have Spaces. But yeah we will investigate it and support filenames with spaces on the future if its possible.

**Comment by wyvern1969** [comment] 2020-02-27 06:59
Hello,
Thanks for your help.
It is clear that this is a problem because many maps have spaces
I close this post and I am awaiting your modification.
Wyvern

**Comment by kremsy** [comment] 2020-02-27 07:07
Issue reopened until its fixed.

**Comment by axelalex2** [comment] 2020-02-28 15:23
`[26-Feb-2020 06:50:05 UTC] PHP Warning: DOMDocument::saveXML(): output conversion failed due to conv error, bytes 0xB2 0x2E 0x4D 0x61 in C:\Program Files (x86)\Serveur Maniaplanet Steph\ManiaControl-0.301\libs\FML\ManiaLink.php on line 601`
reports something different: 0xB2 0x2E 0x4D 0x61 = "².Ma" as substring of "your dirt TM².Map.Gbx", so spaces are not the issue.
It would help if you could send us the map "your dirt TM².Map.Gbx" inside a zip in some way (Discord, GDrive etc.), as i tried a couple other maps with special names, but those all worked for me.

**Comment by wyvern1969** [comment] 2020-03-01 07:26
Hello,
I will not use MAniaControl.
I have no problem with the names of the maps on Uaseco.
I tried to put a plugin and it caused my two servers to bug.
Each time I have to review the checkpoint; php to remove the '
too bad because MAniaControl is easy to use from the server.
Thanks for your help

**Comment by axelalex2** [comment] 2020-03-11 11:16
It would still help us, if you would send us the map in question, even if you decided to use a different server controller. Otherwise i have to close this off.

**Comment by wyvern1969** [comment] 2020-03-12 11:28
I don't know the map that is causing the problem.
I can send you the list of maps from my server.

**Comment by axelalex2** [comment] 2020-03-15 22:59
"your dirt TM².Map.Gbx"
The one, which caused you to send us this issue.

**Comment by axelalex2** [comment] 2020-05-09 13:34
Closed because of no answer, and unreproducability.

**Closed by axelalex2** 2020-05-09 13:34 UTC
Labels: bug
